#530555: [SXA][Headless] Redirects with defined language in source URL don't work
Sitecore/jss pull request #1023
Opened 2022-05-17 12:28 UTC by AntonKechashin

SXA Redirects middleware now checks the patterns for registered locales and updates the URL parameters accordingly.

2022-05-17 13:35 UTC, ambrauer requested changes
See a couple suggestions

2022-05-17 13:35 UTC, ambrauer commented on packages/create-sitecore-jss/src/templates/nextjs-sxa/src/lib/middleware/plugins/redirects.ts
> +    this.locales = nextConfig().i18n.locales;
`locales` should be owned by `RedirectsMiddleware` (another option on `RedirectsMiddlewareConfig`)

2022-05-18 14:29 UTC, ambrauer requested changes
See one comment and also please check lint errors on `sitecore-jss-nextjs` package.

2022-05-19 09:16 UTC, AntonKechashin commented on packages/sitecore-jss-nextjs/src/edge/redirects-middleware.ts
> +  constructor(config: RedirectsMiddlewareConfig, locales: string[]) {
Moved `locales` to `RedirectsMiddlewareConfig`

2022-05-19 14:16 UTC, merged