Updating next to 12.2.4 - and reintroducing babel to avoid swc errors
Sitecore/jss pull request #1124
Opened 2022-08-09 19:19 UTC by art-alexeyenko

Nextjs 12.2.4 fixes some issues - but reintroduces swc exception that happens in containers. This PR reintroduces babelrc file to avoid it.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-08-09 22:04 UTC, sc-addypathania approved these changes
Looks good

2022-08-09 22:09 UTC, sc-addypathania requested changes
Please fix the yarn.lock file. CI build failed.

2022-08-10 19:49 UTC, sc-addypathania approved these changes
Looks good

2022-08-10 19:49 UTC, merged

2022-08-24 12:17 UTC, pzi commented on packages/create-sitecore-jss/src/templates/nextjs/package.json
> +    "next": "^12.2.4",
12.2.5 has been released 12d ago ;)