[Next.js][Multi-site] Dynamic site resolver
Sitecore/jss pull request #1224
Opened 2022-11-01 09:12 UTC by illiakovalenko

## Description / Motivation

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-11-02 15:01 UTC, art-alexeyenko requested changes

2022-11-02 18:43 UTC, ambrauer commented on packages/sitecore-jss/src/site/site-resolver.ts
> +  static resolve = (hostName: string, sitesInfo: SiteData[], fallbackSiteName?: string): string => {
I was expecting the site resolver would perform the fetching of the `SiteData[]` as well (as opposed to a param) which should be possible once the `GraphQLSiteInfoService` is merged from [this PR](https://github.com/Sitecore/jss/pull/1227). However, I can see the benefit to keeping these separate.

What do you thing @art-alexeyenko? Probably a larger discussion we should have... Or something we can always adjust as POC moves along.

2022-11-03 11:32 UTC, illiakovalenko commented on packages/sitecore-jss/src/site/site-resolver.ts
> +    const siteInfo = sitesInfo.find((info) => info.hostName === hostName);
how it should be resolved in this case? which sitename should be returned, or fallback should be provided?

2022-11-03 11:34 UTC, illiakovalenko commented on packages/sitecore-jss/src/site/site-resolver.ts
> +  static resolve = (hostName: string, sitesInfo: SiteData[], fallbackSiteName?: string): string => {
I chose this approach, cause I thought that site-resolver can be used in multiple places

2022-11-03 20:17 UTC, art-alexeyenko commented on packages/sitecore-jss/src/site/site-resolver.ts
> +  static resolve = (hostName: string, sitesInfo: SiteData[], fallbackSiteName?: string): string => {
I don't see much use in anything from SiteData/SiteInfo other than the site name, after it was resolved. Every other piece of data (hostname, language etc) that we may have there would already be known and serve as input into the resolve method.

2022-11-04 15:11 UTC, ambrauer approved these changes
Approving for now. As discussed, we can continue in follow-up items.

2022-11-04 15:12 UTC, merged