[Next.js][React] Link component does not add anchor to the internal links
Sitecore/jss pull request #1228
Opened 2022-11-02 22:56 UTC by sc-addypathania

Add support for anchor attribute for:

- sitecore-jss-react
- sitecore-jss-nextjs

## Description / Motivation

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-11-03 10:24 UTC, illiakovalenko commented
@sc-addypathania Please, double check failed build

2022-11-03 10:25 UTC, illiakovalenko commented
@sc-addypathania Please, update CHANGELOG

2022-11-03 10:26 UTC, illiakovalenko requested changes
Please, update CHANGELOG, otherwise looks good
And I guess that you don't need to cancel azure pipelines build when you are in the PR, you need to that when you merged your changes to release branch

2022-11-03 13:31 UTC, sc-addypathania commented
> Please, update CHANGELOG, otherwise looks good And I guess that you don't need to cancel azure pipelines build when you are in the PR, you need to that when you merged your changes to release branch

I will do that.
I didn't cancel the pipelines. One of the test is failing. I am looking into that.

2022-11-04 19:07 UTC, ambrauer commented on CHANGELOG.md
> -* [EE] Cannot add a new rendering to the newly created ([#902](https://github.com/Sitecore/jss/pull/902))
Looks like your editor made some other formatting changes automatically. Can you please revert these? Maybe stick with the "*" bullet (what we've used thus far) for the new content too.

2022-11-04 19:08 UTC, ambrauer approved these changes
See comment about CHANGELOG, otherwise looks good 👍

2022-11-04 20:27 UTC, merged