#559044: [SXA] fixed rendering dynamic placeholders for splitter components
Sitecore/jss pull request #1292
Opened 2023-01-16 13:42 UTC by matkovskyi

## Description / Motivation
Added pattern and checking for rendering Dynamic placeholders. 

There was bug with rendering splitter components with fix Dynamics placeholders. 

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-01-16 14:53 UTC, StanislavStativa approved these changes

2023-01-16 15:08 UTC, illiakovalenko requested changes
Please, add unit tests to cover new case

2023-01-16 15:08 UTC, illiakovalenko commented on packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
> +/** These patterns need for right rendering Dynamic placeholders.
Comment should on the next line

2023-01-29 22:54 UTC, matkovskyi commented
> Please, add unit tests to cover new case
I added unit test

2023-01-30 05:36 UTC, illiakovalenko commented
@matkovskyi Build is failed, please, fix issues first

2023-01-30 13:39 UTC, matkovskyi commented
> @matkovskyi Build is failed, please, fix issues first

fixed! thanks)

2023-01-31 19:39 UTC, illiakovalenko approved these changes

2023-01-31 19:39 UTC, merged