[Vue] Fix EE error
Sitecore/jss pull request #1338
Opened 2023-02-14 18:31 UTC by sc-addypathania

SSR for EE was not working because `removeAttributeQuotes` was not disabled in the vue `html` `webpack plugin` due to which the html magnification was not working. 

## Description / Motivation

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-02-14 19:45 UTC, art-alexeyenko commented
removeAttributeQuotes was set to false for a reason - see the comments in vue.config on line 13. Setting it to true may cause SSR to stop working (the selector in server/server.js, line 98 could fail).
Please ensure Experience Editor, Preview and SSR proxy work post this change.

2023-02-14 20:33 UTC, art-alexeyenko requested changes
If everything works following the checks - please correct the comment from line 13

2023-02-15 15:30 UTC, sc-addypathania commented
> removeAttributeQuotes was set to false for a reason - see the comments in vue.config on line 13. Setting it to true may cause SSR to stop working (the selector in server/server.js, line 98 could fail). Please ensure Experience Editor, Preview and SSR proxy work post this change.

I think you misunderstood. `removeAttributeQuotes` is set to false not true. I just refactored the code to make sure minify is not `undefined`. All Experience Editor, Preview and SSR proxy work as expected.

2023-02-15 15:49 UTC, art-alexeyenko approved these changes
Then all's well!

2023-02-15 16:02 UTC, merged