#536289: [SXA] added nextjs-sxa-scaffold initializer
Sitecore/jss pull request #1420
Opened 2023-04-05 16:23 UTC by matkovskyi

- [ ] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)

## Description / Motivation

Added a new option(nextjs-sxa scaffold component action) for nextjs initializer. 

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-04-05 18:03 UTC, ambrauer reviewed
@matkovskyi any reason not to just include this with the existing `nextjs-sxa` initializer add-on?

2023-04-06 06:57 UTC, matkovskyi commented
> @matkovskyi any reason not to just include this with the existing `nextjs-sxa` initializer add-on?

Yes, you're right! I fixed it

2023-04-06 07:52 UTC, sc-dawidrutkowski requested changes

2023-04-06 07:52 UTC, sc-dawidrutkowski commented on packages/create-sitecore-jss/src/templates/nextjs-sxa/scripts/templates/component-src.ts
@matkovskyi That is not enough. We must scaffold the basic structure of the SXA component including:
- usage of `props.params.styles`
- usage of `props.params.RenderingIdentifier`
- usage of `export const Default` which stands for the default rendering variant
No need of creating two variants, take a look at what e.g.: the Promo component looks like.

2023-04-06 10:50 UTC, illiakovalenko commented
@matkovskyi Please, also update CHANGELOG.md file to include your PR. We started to update Changelog for each PR, so it makes easier for us to start release processes

2023-04-06 10:51 UTC, matkovskyi commented on packages/create-sitecore-jss/src/templates/nextjs-sxa/scripts/templates/component-src.ts
fixed

2023-04-06 10:58 UTC, sc-dawidrutkowski approved these changes

2023-04-06 11:45 UTC, illiakovalenko requested changes

2023-04-06 11:45 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/nextjs-sxa/scripts/scaffold-component.ts
> +/*
I'm not sure that I can see any difference of this file and nextjs/scripts/scaffold-component.ts that we have. Essentially this file is not needed

2023-04-06 11:47 UTC, illiakovalenko requested changes

2023-04-06 11:47 UTC, illiakovalenko commented on CHANGELOG.md
> +* `[templates/nextjs-sxa]` Add scaffold components action `jss scaffold {nameOfComponent}` ([#1420](https://github.com/Sitecore/jss/pull/1420))
```suggestion
* `[templates/nextjs-sxa]` Add custom template for _jss scaffold_ ([#1420](https://github.com/Sitecore/jss/pull/1420))
```

2023-04-06 11:48 UTC, illiakovalenko commented on CHANGELOG.md
> +* `[templates/nextjs-sxa]` Add scaffold components action `jss scaffold {nameOfComponent}` ([#1420](https://github.com/Sitecore/jss/pull/1420))
@matkovskyi  It should be added under specific section: Bug Fix, Improvements - you can see example in a same file below.
In your case it's improvement

2023-04-06 11:58 UTC, merged