#585891: fixed 404/500 added DISABLE_SSG_FETCH params
Sitecore/jss pull request #1496
Opened 2023-05-24 14:19 UTC by matkovskyi

- [ ] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated

## Description / Motivation

Added condition DISABLE_SSG_FETCH for 404/500 pages for to enable full ISR (Incremental Static Regeneration) flow 

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-05-24 21:18 UTC, ambrauer requested changes

2023-05-25 19:55 UTC, ambrauer approved these changes

2023-05-25 19:56 UTC, merged

2023-06-06 15:01 UTC, bewards commented
What is the `headLinks` code for? I see this code in the commit, but looks like the release package somehow omits it.

2023-06-06 15:12 UTC, illiakovalenko commented
@bewards I referenced this PR, since I pulled changes from here, but actual commit for patch is: https://github.com/Sitecore/jss/commit/66a032ab05b86503ecad509ae6b41c5d8d310347

2023-06-06 15:15 UTC, bewards commented
Thanks for the clarification @illiakovalenko !