[angular-xmcloud] Introduce Angular SXA Richtext component
Sitecore/jss pull request #1864
Opened 2024-07-30 02:34 UTC by sc-addypathania

- [ ] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-07-31 11:28 UTC, yavorsk approved these changes
Looks good!

2024-08-01 10:48 UTC, illiakovalenko requested changes
See some questions below
Did you try to start the app using the implemented component? I'm wondering on how it could compile if _field_ property type doesn't match a real type

2024-08-01 10:48 UTC, illiakovalenko commented on CHANGELOG.md
> +* `[create-sitecore-jss]``[template/angular-sxa]` Angular SXA components ([#1864](https://github.com/Sitecore/jss/pull/1864))
Can you move this comment under [line:18](https://github.com/Sitecore/jss/pull/1864/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR18)? Let's collect the components under the existing feature
```suggestion
* `[create-sitecore-jss]``[template/angular-xmcloud]` Angular SXA components ([#1864](https://github.com/Sitecore/jss/pull/1864))
```

2024-08-01 10:48 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/richtext/richtext.component.ts
> +  text: string;
_text_ can't be a string, since it's a field

2024-08-01 10:48 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/richtext/richtext.component.ts
> +  id: string;
is it optional? since it can be _undefined_ in a template, as I can see

2024-08-01 10:48 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/richtext/richtext.component.ts
> +  styles: string;
Optional as well?

2024-08-02 10:23 UTC, illiakovalenko approved these changes
👍

2024-08-02 10:24 UTC, merged