[angular-xmcloud] Introduce column-splitter component for angular
Sitecore/jss pull request #1889
Opened 2024-08-14 04:25 UTC by sc-addypathania

- [ ] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation
Add `ColumnSplitterComponent` to angular xmcloud

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-08-14 10:35 UTC, illiakovalenko requested changes
See two notes:
1. Please, make sure to verify your changes before opening the PR, since the component is not rendered as expected (I tested locally). I created a bug in our dashboard
![image](https://github.com/user-attachments/assets/d084593a-c11f-433c-a77e-9d65a93b87c6)
2. Yes - we are reusing (copying) SXA's components functionality from Next.js. But if we have some room for improvement or ways how to make it more prettier it should be applied

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.ts
> +    return [
```suggestion
    return Array.from({ length: 8 }, (_, i) => this.rendering.params[`ColumnWidth${i + 1}`]);
```

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.ts
> +    return [
```suggestion
    return Array.from({ length: 8 }, (_, i) => this.rendering.params[`Styles${i + 1}`]);
```

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.ts
> +  ngOnInit() {
ngOnInit is not needed if you are not defining something there, the same for "OnInit" interface

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +﻿<div [ngClass]="['row', 'component', 'column-splitter', columnSplitterStyles]" [attr.id]="id || null">
"class" attribute is not computed, so it doesn't make sense to use "[ngClass]"
Do we need to set a fallback value for "id" to "null"? Do we even need to set a fallback value?
```suggestion
﻿<div class="row component column-splitter columnSplitterStyles" [attr.id]="id || null">
```

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +    <div [ngClass]="[columnWidths[+ph - 1], columnStyles[+ph - 1] || ''].join(' ').trim()">
let's compute that inside of "component class" instead, it's too much to keep in markup

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +      <div [ngClass]="['row']">
This value is not computed
```suggestion
      <div class="row">
```

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +          [key]="index"
Not sure if "sc-placeholder" accepts "index", I didn't find this property

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +          [name]="'column-' + ph + '-{*}'"
let's compute the placeholder name inside of "component class" instead, you can define a function

2024-08-14 10:35 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.html
> +  <div *ngFor="let ph of enabledPlaceholders; let index = index">
Not sure if "index" is needed, see my comment below

2024-08-15 17:59 UTC, art-alexeyenko approved these changes
Looks good to me. Thanks Addy!

2024-08-15 19:21 UTC, merged