[sitecore-jss-dev-tools] Update logic of generating used sitecore packages metadata
Sitecore/jss pull request #1949
Opened 2024-10-15 12:23 UTC by yavorsk

- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [x] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation

Previously getMetadata() was generating the metadata about the used sitecore packages through traversing the node-modules folder of the application. This approach does not work in a monorepo setup.
This PR addresses the problem by making some updates of the logic that gathers the metadata - it uses `package-lock.json` (if already not present in the app root - create it and remove it after it is not needed any more) to gather the information of the used sitecore packages and their exact version.

## Testing Details

- [ ] Unit Test Added
- [x] Manual Test/Other (Please elaborate) Test standalone, in monorepo, in other monorepos

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-10-15 20:49 UTC, art-alexeyenko requested changes
Would it also make sense to cleanup some of the test-data package lock files for better maintainability?

2024-10-16 06:47 UTC, yavorsk commented on packages/sitecore-jss-dev-tools/src/templating/metadata.ts
> +    packageLock = JSON.parse(fs.readFileSync(packageLockPath, 'utf8'));
in my tests, when it's generated with `--workspaces true` package-lock gets created in the root of the monorepo so app won't find it and generate its own.

2024-10-16 13:48 UTC, yavorsk commented on packages/sitecore-jss-dev-tools/src/templating/metadata.ts
> +  if (!packageLockIsAvailable) {
The problem is that going through node_modules can produce a result and we would not be certain if it is correct in monorepo setup..

2024-10-22 09:45 UTC, illiakovalenko commented on packages/sitecore-jss-dev-tools/src/templating/metadata.ts
> +const dependencyTypes = ['dependencies', 'devDependencies', 'peerDependencies'];
Not relevant anymore

2024-10-22 11:45 UTC, yavorsk commented on CHANGELOG.md
> +* `[sitecore-jss-dev-tools]` getMetadata() now uses `npm query` command to get the list and exact versions of packages. this solution works for monorepo setups ([#1949](https://github.com/Sitecore/js
yep makes sense

2024-10-22 12:47 UTC, art-alexeyenko approved these changes

2024-10-22 19:20 UTC, merged