[angular][xmcloud] Init CloudSDK on browser
Sitecore/jss pull request #1952
Opened 2024-10-16 23:01 UTC by art-alexeyenko

- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation
- Initializes CloudSDK on browser for Angular app
- Allows for other parts of app to use events etc

## Testing Details
- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-10-17 07:14 UTC, yavorsk requested changes
Looks good! 
See just one thing regarding the component description.
Also - does it make sense to rename the component or the selector for consistency - `cloud-sdk-init` vs `app-cloudsdk-init`?

2024-10-17 07:14 UTC, yavorsk commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/cloud-sdk-init.component.ts
> + * Component that renders editing scripts and client data for the current page in Sitecore Editor.
This description should be updated.

2024-10-21 10:07 UTC, yavorsk commented
Should we add the sitecore-cloudsdk dependencies to angular-xmcloud as well?

2024-10-21 15:01 UTC, art-alexeyenko commented
> Should we add the sitecore-cloudsdk dependencies to angular-xmcloud as well?

true - it's now on angular side only

2024-10-22 07:13 UTC, yavorsk approved these changes

2024-10-22 07:14 UTC, merged