[Chore] Update to nodejs v22
Sitecore/jss pull request #1975
Opened 2024-11-17 17:52 UTC by art-alexeyenko

- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated
- [ ] Upgrade guide entry added - TBA

## Description / Motivation
Update monorepo and samples to use node 22
- Update engine to `node>=22`
- Update `@types/node` deps to `22.9.0`
- Update typescript across the board to `5.6.3` for compatibility
  - This also required updates for `@typescript-eslint`
  - `@typescript-eslint` plugin updated to version 8, some rules adjusted
  - `@stylistic/eslint-plugin-ts` dep added to keep using rules removed from `@typescript-eslint`
  - `eslint` version has been bumped to 8 for compatibility. v9 introduces some breaking changes in configuration and will be upgraded to later
- Updates to react, nextjs
  - "cheerio": "1.0.0-rc.3" resolution has been added to prevent test run failing for enzyme (https://github.com/enzymejs/enzyme/issues/2609)
  - `react` and `@types/react` versions locked to `~18.2` due to some breaking changes in react types for `18.3` when using node 22
- angular updates
  - upgraded `sinon`

Known issue: 
- `(node:8860) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.` error will pop up in console when building packages or apps. This does not affect app execution, and is caused by dependencies of dependencies JSS uses. This error will go away in time, as dependencies are updates (i.e. for `http-proxy-middleware` https://github.com/chimurai/http-proxy-middleware/issues/1058).

## Testing Details
- [x] Unit Test Adjusted
- [x] Manual Test/Other (Please elaborate) - build, lint, test, run samples

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

2024-11-17 17:56 UTC, art-alexeyenko commented on packages/create-sitecore-jss/src/templates/angular/package.json
> +    "typescript": "~5.4.0"
angular sample will continue using typescript 5.4.0 for compatibility with current Angular version

2024-11-17 17:59 UTC, art-alexeyenko commented on packages/create-sitecore-jss/src/templates/nextjs-multisite/src/lib/middleware/plugins/multisite.ts
> +    // @ts-expect-error A 'Property '[INTERNALS]' is missing' error can occur in monorepo setups with peerDeps.
This note is added to fix the error occurring during nextjs build. Full text:
```
Type error: Property '[INTERNALS]' is missing in type 'import("C:/Wok/jss/jss/packages/sitecore-jss-nextjs/node_modules/next/dist/server/web/spec-extension/response").NextResponse<unknown>' but required in type 'import("C:/Wok/jss/jss/samples/nextjs/node_modules/next/dist/server/web/spec-extension/response").NextResponse<unknown>'.
```

This is a very confusing error, as the dependency installed in jss-nextjs package and nextjs sample are identical (version, contents, code, all of it). This makes me believe it is a yarn monorepo issue - yarn does not install peer dependencies - so we need to install next as devDep explicitly in `sitecore-jss-nextjs` and this causes confusion (as usually there would only be one copy of next).

2024-11-19 07:47 UTC, yavorsk reviewed
Great work! 
The changes seem reasonable to me, I also verified build, lint, unit tests on my machine.
The only thing that looks off to me is the `@ts-expect-error` statements. Maybe we should investigate this in separate ticket?

2024-11-19 12:00 UTC, illiakovalenko requested changes
Great job on this update! 👍 
Please, review my comments/questions below

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss-react/package.json
"Node" field should be updated to v22
``` 
"engines": {
    "node": ">=22"
  },
```

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
> +   * @default
This tag is not needed anymore, we just need to mention in description that by default it uses "query" variable

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss/src/i18n/graphql-dictionary-service.ts
> +   * @default
This tag is not needed anymore, we just need to mention in description that by default it uses "siteQuery" variable

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss-react/package.json
> +    "react": "~18.2.0",
See my question below, related to "react" dependency

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss-nextjs/src/utils/utils.ts
> + * @default
Can be removed, this tag has a different purpose

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss-nextjs/package.json
> +    "react": "~18.2.0",
Same question as in "sitecore-jss-react/package.json" - I think that we can't really "fix" this version. Some customers may already use latest "react" and this change will affect them. This change is kind of "workaround"

2024-11-19 12:00 UTC, illiakovalenko commented on packages/sitecore-jss-angular/src/components/rendering-field.ts
> +/* eslint-disable @typescript-eslint/no-empty-object-type */
Can be just defined at the start of the file, right? Since you have 3 occurrences already

2024-11-19 12:00 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/templates/nextjs-multisite/src/lib/middleware/plugins/multisite.ts
> +    // @ts-expect-error A 'Property '[INTERNALS]' is missing' error can occur in monorepo setups with peerDeps.
Can you look at our "monorepo" configuration and apply something there? **nextjs\src\lib\next-config\plugins\monorepo.js**
This message doesn't look good and it's present across multiple middleware plugins, this should be solved rather left as a notification about the problem

2024-11-19 12:00 UTC, illiakovalenko commented on packages/create-sitecore-jss/src/common/processes/transform.ts
> + * determines files for copy
```
/**
 * Handles each template file and applies ejs renderer, also:
 * - Determines files for copy.
 * - Determines files for skip.
 * if some files already exist:
 *   - merges package.json files
 *   - concatenates .env files
 *   - compares diffs
 * @param {string} templatePath path to the template
 * @param {BaseArgs} answers CLI arguments
 * @param {TransformOptions} options custom options
 */
```

2024-11-19 14:43 UTC, art-alexeyenko commented on packages/create-sitecore-jss/src/templates/nextjs-multisite/src/lib/middleware/plugins/multisite.ts
> +    // @ts-expect-error A 'Property '[INTERNALS]' is missing' error can occur in monorepo setups with peerDeps.
Alas, adding `next` to externals does not work. It is a typescript, you will also see it when editing in vscode.
Do you know a way to somehow reuse one single package via tsconfig configuration?

2024-11-19 16:20 UTC, illiakovalenko approved these changes

2024-11-19 19:26 UTC, art-alexeyenko commented on packages/create-sitecore-jss/src/templates/nextjs/package.json
> +    "typescript": "~5.4.0",
similar to Angular, later typescript does not behave well with next version we use. To be updated further later.

2024-11-19 19:40 UTC, merged