[templates/angular-xmcloud][templates/node-xmcloud-proxy] Angular and XM Cloud Proxy Readme updates
Sitecore/jss pull request #1989
Opened 2024-12-02 11:32 UTC by yavorsk

- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [x] Changelog updated
- [ ] Upgrade guide entry added

## Description / Motivation

This PR includes Angular for XM Cloud and XM Cloud Node Proxy Readme updates, according to lates feedback from PSS.

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [x] Chore
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-12-02 12:07 UTC, stasmaxymov commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +This Single Page Application (SPA) built with Angular is designed to be fully compatible with XM Cloud, incorporating several key add-ons and features to streamline the development process and enable
typo, capital letter:  "When used with the Node **The**"

2024-12-02 12:08 UTC, stasmaxymov commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +Follow the steps below to deploy your starter SPA (instructions are for Angular SPA, more to follow in the future). The Neylify deployment has been tested and can be used as editing host in XM Cloud.
typo: Neylify

2024-12-06 16:56 UTC, mattcantcode requested changes
Most comments relate to Angular. I added some to the Node proxy readme too, but these are mostly addressed in this Word doc: https://sitecore1-my.sharepoint.com/:w:/g/personal/matp_sitecore_net/EYtEb9QYkGFLtNAW5AcyTU8BVp8ciAuaKI4g9Qxz4eY3Tg?e=s0Koma

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +> If you encounter any issues or bugs, please submit a new issue in the [Jss GitHub Repo](https://github.com/Sitecore/jss)
JSS

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +> Sitecore JSS Angular App for XM Cloud. For the current release this feature is in public beta.
"For the current release this feature is in public beta" > "This feature is currently in public beta."

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +- `XM Cloud Angular`: simplifies connecting the application to XM Cloud and configuring the integration of multiple composable Sitecore products, provides out of the box helper components.
"provides out of the box helper components." > "and provides out-of-the-box helper components."

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +- `XM Cloud Proxy`: Adds integration with XM Cloud for the JSS SPA applications and enables editing, personalization and A/B component testing support, see [XM Cloud Proxy](../node-xmcloud-proxy/)
", see [XM Cloud Proxy](../node-xmcloud-proxy/)" > ". See [XM Cloud Proxy](../node-xmcloud-proxy/) for more information."

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +The supported key features are as follows:
"The following key features are supported:"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +- `Internationalization` support
Add full-stop.

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +> - BYOC components
Confirm with Anastasia whether we need to say this in addition to "The XM Cloud Components application", as Liz stated this is the same thing.

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +> - XM Cloud Components application
"The XM Cloud Components application"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +To build and run in production mode you need to have your angular app side by side with the [Node XM Cloud proxy](../node-xmcloud-proxy/).
"Angular"

What do we mean by "side by side"?

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +The following environment variables can be set to configure the angular app. You can use the `.env` file located in the root of the app or set these directly in the environment (for example, in conta
"can be used to configure"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +| `SITECORE_EDGE_CONTEXT_ID`                              | The Context ID, which covers many system configurations, required for connecting to the XM Cloud back end. This is an XM Cloud system envir
"...is required for connecting to the XM Cloud back end."

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +| `SITECORE_SITE_NAME`                              | The name of your site. This variable overrides the config.appName defined in the package.json file. You can find this value in the Sites dashboar
Check , and ` at end of this line.

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +This Node.js-based proxy app is the backbone for enabling seamless integration between XM Cloud and various SPA frameworks like React, Angular, or Vue laying the groundwork for future JSS starter kit
"A/B/n"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +- `XM Cloud proxy personalization` with embedded personalization and Component A/B Testing support.
"component A/B/n testing"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +> - BYOC components
As elsewhere, please confirm with Anastasia whether we need to say BYOC here as well as the components app.

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +> - XM CLoud Components application
"The XM Cloud Components application"

2024-12-06 16:56 UTC, mattcantcode commented on packages/create-sitecore-jss/src/templates/node-xmcloud-proxy/README.md
> +The following environment variables can be set to configure the Node XM Cloud Proxy app instead of modifying `config.js`. You can use the `.env` file located in the root of the app or set these direc
"can be used to configure"

2024-12-06 19:33 UTC, anasplat commented on packages/create-sitecore-jss/src/templates/angular-xmcloud/README.md
> +> If you encounter any issues or bugs, please submit a new issue in the [Jss GitHub Repo](https://github.com/Sitecore/jss)
Angular for XM Cloud

2024-12-06 21:12 UTC, merged