Add procedures for getting-started/walkthrough-jsscreate
Sitecore/jss pull request #577
Opened 2021-02-18 17:02 UTC by AncaIO

## Description

## Motivation

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [ ] I have read the Contributing guide.
- [ ] My code follows the code style of this project.
- [ ] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

2021-02-18 17:03 UTC, AncaIO commented
@nickwesselman  I took "procedural" quite literally. I hope that's ok. If we have anything to say about the CLI we have https://jss.sitecore.com/docs/fundamentals/cli.

2021-02-18 20:25 UTC, nickwesselman commented on docs/data/routes/docs/nextjs/getting-started/walkthrough-jsscreate/en.md
> +## TL;DR
I love it :)

2021-02-18 20:29 UTC, nickwesselman requested changes

2021-02-18 20:29 UTC, nickwesselman commented on docs/data/routes/docs/nextjs/getting-started/walkthrough-jsscreate/en.md
> +Pulling content in your JSS application from Sitecore  and using JSS in production, will require a Sitecore instance.
"Pulling" isn't really accurate, maybe something like

> Deploying your code-first artifacts and content to Sitecore, WYSIWYG editing, and use of JSS in production will require a Sitecore instance.

2021-02-18 20:29 UTC, nickwesselman commented on docs/data/routes/docs/nextjs/getting-started/walkthrough-jsscreate/en.md
> +1. [Setup JSS Server Components](https://jss.sitecore.com/docs/getting-started/jss-server-install).
Yeah I think linking to these for now is good, once we restructure all the docs to focus on Next.js, we can move / reword these articles as well.

2021-02-18 20:29 UTC, nickwesselman commented on docs/data/routes/docs/nextjs/getting-started/walkthrough-jsscreate/en.md
> +We recommend this approach for Sitecore developers that use the [code-first developer workflow](https://jss.sitecore.com/docs/fundamentals/dev-workflows/code-first).
"or who wish to evaluate the JSS developer experience without installing Sitecore" ?

2021-02-18 20:30 UTC, nickwesselman commented
> @nickwesselman I took "procedural" quite literally. I hope that's ok. If we have anything to say about the CLI, we have https://jss.sitecore.com/docs/fundamentals/cli.

Straightforward and simple, I like it.

2021-02-19 17:24 UTC, nickwesselman approved these changes

2021-02-22 17:27 UTC, merged