[JSS] [React] - fix: type defs of React Placeholder render props
Sitecore/jss pull request #589
Opened 2021-02-22 16:05 UTC by Bram-Zijp

The type definitions of the React Placeholder component were not user-friendly/stable. I ensured only one type was used and returned (`React.ReactElement`).

## Motivation

Consistent types. No hacky type casting is done/required.

## How Has This Been Tested?

Remove type casts and get TypeScript to test for you :+1: 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [x] I have read the Contributing guide.
- [?] My code follows the code style of this project. -> This should be done automatically. I didn't see any code guidelines but free improvement remains free improvement. Feel free to adjust this mr to your liking.
- [ ] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

2021-02-24 18:01 UTC, anastasiya29 commented
This PR did not compile in CI

This is the error:
```
src/components/Placeholder.tsx(68,37): error TS2345: Argument of type '(ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null)[]' is not assignable to parameter of type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>[]'.

Type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.
2021-02-22T16:37:49.2564342Z     Type 'null' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>'.

src/components/Placeholder.tsx(70,32): error TS2345: Argument of type '(ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> | null)[]' is not assignable to parameter of type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>[]'.
```
Looking at the changes, it seems you may have been trying to fix some issues that have been covered here:
#459 [sitecore-jss-react] Change propType of missingComponentComponent from React.SFC (deprecated) to React.FC.
#538  [sitecore-jss-react] Change propType of errorComponent from React.SFC (deprecated) to React.FC.

Please let us know if you identified another issue

2021-02-24 18:02 UTC, anastasiya29 requested changes
Need to resolve build issues

2021-02-24 21:24 UTC, Bram-Zijp commented
I am not referencing any issues. This MR is not interested in SFC nor FC. The changes to the `React propTypes` are only done to improve the code base and are not the purpose of this MR. The main problem I had is the illustrated below;

Difference between rendering an element and a component:

```
const Component = () => <div />
const element = <Component />

// how to render the above:

const Example = () => 
  <>
     <Component />
     {element}
  </>
```

The `Placeholder` `renderEach` prop was passing a React element by default. When an error occurs it would pass a component instead.

As you can see this is not a difference you want the consumers of this repo to handle. Considering this repo can return consistent type of React components/elements, this should be a no brainer.

I will take a look at the type errors origin. This is probably a problem wide spread over your code base. I only noticed the Placeholder's function `renderEach` being typed on a smelly way. It might be worth letting a Sitecore TypeScript dev take a look at these changes.

2021-04-25 16:03 UTC, Bram-Zijp commented
I was just looking at this MR again and I am unable to reproduce these error's locally. Please take over this MR or let me know how to reproduce locally. Perhaps it's good to add these lint steps to the docs.

2022-10-11 18:16 UTC, closed without merging