[Vue] Use fragments by default with sc-placeholder
Sitecore/jss pull request #742
Opened 2021-07-08 13:06 UTC by illiakovalenko

## Description / Motivation

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

2021-07-08 16:05 UTC, CobyPear requested changes
I left some suggested grammar edits, but overall I think the idea is clear!

2021-07-09 06:24 UTC, illiakovalenko commented on docs/data/routes/docs/client-frameworks/vue/vue-placeholders/en.md
> +The `Placeholder` component doesn't render wrapper around child components, it happens because of [fragments technique](https://v3.vuejs.org/guide/migration/fragments.html#overview).
Done

2021-07-09 06:26 UTC, illiakovalenko commented on docs/data/routes/docs/client-frameworks/vue/vue-placeholders/en.md
> +When you iterate the component array in your template, Vue will render the components where you emit them, or you can achive it using `Placeholder` component. If you emit the placeholder contents wit
Done

2021-07-09 06:27 UTC, illiakovalenko commented on docs/data/routes/docs/client-frameworks/vue/vue-placeholders/en.md
> +In the preceding sample it's expected that the component hierarchy is `Carousel` -> `Slide`. If you wished to add the `slide` components using a placeholder, so that Sitecore could define them, and t
Done

2021-07-09 12:34 UTC, CobyPear approved these changes

2021-07-09 12:35 UTC, merged