Update README files with new doc links and current product names
Sitecore/jss pull request #869
Opened 2021-12-06 11:00 UTC by ancaemcken

## Description / Motivation

## Testing Details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-12-06 13:48 UTC, CobyPear approved these changes
Looks good!

2021-12-06 14:16 UTC, ambrauer requested changes
Is there any way we can avoid the add'l ongoing release maintenance (TODOs) introduced with these version-specific doc URLs? For example, use  https://doc.sitecore.com/xp/en/developers?
Otherwise looks great.

2021-12-06 14:16 UTC, ambrauer commented on packages/sitecore-jss-dev-tools/README.md
>  Consult the [Sitecore JSS documentation](https://jss.sitecore.com) for further details.
Missed a URL here?

2021-12-06 15:55 UTC, ancaemcken commented
@ambrauer Not at this time. I'm hoping we will soon have "latest" version tag :crossed_fingers:  In the meantime, I am more than happy to make the updates in these files (which is why I added the TODOs so I can quickly find the items that need updating). Hopefully, we will only have to update these once or twice before we get a "latest" version in the docs.

2021-12-06 16:50 UTC, ambrauer approved these changes

2022-01-04 08:23 UTC, ancaemcken commented on packages/sitecore-jss-dev-tools/README.md
>  Consult the [Sitecore JSS documentation](https://jss.sitecore.com) for further details.
Oops :D

2022-01-04 14:30 UTC, merged